### PR TITLE
Merge together sass watch and serve

### PR DESCRIPTION
**Pull request by budavariam**
#15 

Based on: https://egghead.io/lessons/11ty-add-sass-compiling-and-watch-for-changes-in-eleventy-11ty

Notes:
- I think the pipeline should not directly modify files in the `_site` folder, that should handled by eleventy, thus I save the generated files to css folder, and `passthroughcopy` to the proper location
- I'm not sure what `netlify dev` does, I hope these changes did not break the workflow
- new dependency: [npm-run-all](https://www.npmjs.com/package/npm-run-all), cross platform, seems legit by their user count
- I do not trust the globstar in the tutorial's `build:*`, we have to run sass first thus `"build": "npm-run-all build:sass build:eleventy",` seems more reliable

### CODE REVIEW

**Comment by Stefanye** [comment]
Already got a solution for this, I just didn't had time to test it. I'll check your too, thank you!

**Comment by Stefanye** [comment]
Been playing around with examples like yours and [this one](https://stedman.dev/2020/05/11/watching-sass-in-eleventy/), but they all result in a strange behavior: sometimes I need to save twice on the sass files to see the effect on my site. I'm not sure this is caused by the fact that I'm using Windows and it has permission problems, or something else.

**Comment by Stefanye** [comment]
After several tests I've merged my solution which is quiet similar to yours, it just required some fine tuning. Thanks for the help and sorry for not choosing this one :( :)

**Comment by budavariam** [comment]
Thanks for checking it out! It was fooish of me to assume that it'd work in windows out of the box.
I'm glad you found a working solution.

**Comment by Stefanye** [comment]
Windows is just Windows, don't feel bad for not thinking about it :D

**Pull request closed without merging**
